WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM hours WHERE HOUR < 23
)
SELECT 
    h.HOUR, 
    COALESCE(COUNT(a.DATETIME), 0) COUNT
FROM 
    hours h
LEFT JOIN 
    ANIMAL_OUTS a ON h.hour = HOUR(a.DATETIME)
GROUP BY 
    h.HOUR
ORDER BY 
    h.HOUR;